name: Build Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - "client-android/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Build APK
        run: |
          cd client-android
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: smartvpn-apk
          path: client-android/build/app/outputs/flutter-apk/app-release.apk